# Generated by Django 6.0.6 on 2026-06-09 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoProductionTreaty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_a', models.CharField(max_length=2)),
                ('country_b', models.CharField(max_length=2)),
                ('treaty_name', models.CharField(max_length=255)),
                ('convention_reference', models.CharField(blank=True, max_length=100)),
                ('min_producer_countries', models.IntegerField(default=2)),
                ('min_budget_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eligible_incentive_types', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField()),
            ],
            options={
                'db_table': 'co_production_treaties',
                'unique_together': {('country_a', 'country_b')},
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('region', models.CharField(max_length=50)),
                ('incentive_type', models.CharField(choices=[('CASH_REBATE', 'Cash Rebate'), ('TAX_CREDIT', 'Tax Credit'), ('TAX_SHELTER', 'Tax Shelter'), ('GRANT', 'Grant')], max_length=20)),
                ('base_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_rebate_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_capped', models.BooleanField(default=False)),
                ('is_stackable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('official_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'territories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QualifiedSpendMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_category_pattern', models.CharField(max_length=255)),
                ('mapped_eligible_category', models.CharField(max_length=100)),
                ('eligibility_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('requires_local_vendor', models.BooleanField(default=False)),
                ('requires_local_crew', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_mappings', to='territories.territory')),
            ],
            options={
                'db_table': 'qualified_spend_mappings',
            },
        ),
        migrations.CreateModel(
            name='TerritoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('MIN_SPEND', 'Minimum Spend'), ('ELIGIBLE_CATEGORY', 'Eligible Category'), ('CULTURAL_TEST', 'Cultural Test'), ('STACKING', 'Stacking Rule'), ('LOCAL_SPEND', 'Local Spend Requirement'), ('CREW_REQUIREMENT', 'Crew Requirement')], max_length=30)),
                ('configuration', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='territories.territory')),
            ],
            options={
                'db_table': 'territory_rules',
                'ordering': ['priority', 'rule_type'],
            },
        ),
    ]
