# Generated by Django 5.0.14 on 2026-06-11 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("territories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="territory",
            name="animation_eligible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="territory",
            name="documentary_eligible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="territory",
            name="is_regional_stacking_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="territory",
            name="loan_against_rebate_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="territory",
            name="min_local_crew_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="territory",
            name="provincial_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="territory",
            name="rebate_timing_months_max",
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name="territory",
            name="rebate_timing_months_min",
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name="territory",
            name="sci_fi_eligible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="territory",
            name="streaming_eligible",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="coproductiontreaty",
            name="country_a",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="coproductiontreaty",
            name="country_b",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="territory",
            name="country_code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="territoryrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("MIN_SPEND", "Minimum Spend"),
                    ("ELIGIBLE_CATEGORY", "Eligible Category"),
                    ("CULTURAL_TEST", "Cultural Test"),
                    ("STACKING", "Stacking Rule"),
                    ("LOCAL_SPEND", "Local Spend Requirement"),
                    ("CREW_REQUIREMENT", "Crew Requirement"),
                    ("TREATY_BONUS", "Co-production Treaty Bonus"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PolicyAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("RATE_CHANGE", "Rate Change"),
                            ("RULE_CHANGE", "Rule Change"),
                            ("NEW_TERRITORY", "New Territory"),
                            ("SUSPENSION", "Program Suspended"),
                            ("REINSTATEMENT", "Program Reinstated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("previous_value", models.CharField(blank=True, max_length=100)),
                ("new_value", models.CharField(blank=True, max_length=100)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "territory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_alerts",
                        to="territories.territory",
                    ),
                ),
            ],
            options={
                "db_table": "policy_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TerritoryComplianceChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "Document Required"),
                            ("APPLICATION", "Application/Registration"),
                            ("MILESTONE", "Production Milestone"),
                            ("AUDIT", "Audit/Certification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "deadline_type",
                    models.CharField(
                        choices=[
                            ("BEFORE_SHOOT", "Before Principal Photography"),
                            ("DURING_SHOOT", "During Production"),
                            ("AFTER_SHOOT", "After Wrap"),
                            ("AFTER_DELIVERY", "After Delivery/Release"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "territory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_items",
                        to="territories.territory",
                    ),
                ),
            ],
            options={
                "db_table": "territory_compliance_checklists",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TerritoryPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("cpa", "CPA / Tax Advisor"),
                            ("line_producer", "Line Producer"),
                            ("legal", "Legal Counsel"),
                            ("fixer", "Local Fixer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("bio", models.TextField(blank=True)),
                ("is_vetted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "territory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partners",
                        to="territories.territory",
                    ),
                ),
            ],
            options={
                "db_table": "territory_partners",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GenreIntelligenceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("sci_fi", "Sci-Fi"),
                            ("animation", "Animation"),
                            ("documentary", "Documentary"),
                            ("horror", "Horror"),
                            ("streaming", "Streaming/Series"),
                            ("drama", "Drama"),
                            ("action", "Action"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bonus_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("eligibility_notes", models.TextField(blank=True)),
                ("spend_category_multipliers", models.JSONField(default=dict)),
                (
                    "territory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genre_profiles",
                        to="territories.territory",
                    ),
                ),
            ],
            options={
                "db_table": "genre_intelligence_profiles",
                "unique_together": {("territory", "genre")},
            },
        ),
    ]
