# Generated by Django 5.0.14 on 2026-06-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("territories", "0002_phase1_model_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="territory",
            name="film_commission",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="territory",
            name="film_commission_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="territory",
            name="government_support",
            field=models.TextField(
                blank=True,
                help_text="Notes on local government / board support, soft money, and on-the-ground assistance.",
            ),
        ),
        migrations.AddField(
            model_name="territory",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="territory",
            name="local_associations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of {name, url} for film/media associations and guilds.",
            ),
        ),
        migrations.AddField(
            model_name="territory",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=8, null=True
            ),
        ),
    ]
