# Generated by Django 5.0.14 on 2026-06-09 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("territories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("USER", "User Initiated"),
                            ("SCHEDULED", "Scheduled"),
                            ("POLICY_CHANGE", "Policy Change"),
                        ],
                        default="USER",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="projects.budget",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "analyses",
                "db_table": "analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                (
                    "qualified_spend_total",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "estimated_rebate",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "estimated_rebate_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "logistics_premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("net_benefit", models.DecimalField(decimal_places=2, max_digits=15)),
                ("payback_timeline_months", models.IntegerField(blank=True, null=True)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="analysis.analysis",
                    ),
                ),
                (
                    "territory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="territories.territory",
                    ),
                ),
            ],
            options={
                "db_table": "analysis_results",
                "ordering": ["rank"],
            },
        ),
    ]
