# Generated by Django 5.0.14 on 2026-06-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="financing_benefit_estimate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="loan_against_rebate_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="rebate_timing_months",
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="recoupment_priority",
            field=models.CharField(
                choices=[
                    ("first", "First Position"),
                    ("shared", "Shared"),
                    ("last", "Last Position"),
                ],
                default="shared",
                max_length=10,
            ),
        ),
    ]
