# Generated by Django 5.0.14 on 2026-06-10 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("EXCEL", "Excel"), ("JSON", "JSON")],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="reports/%Y/%m/")),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("download_count", models.IntegerField(default=0)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="analysis.analysis",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-generated_at"],
            },
        ),
    ]
