# Generated by Django 6.0.6 on 2026-06-09 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('XLSX', 'Excel')], max_length=10)),
                ('file', models.FileField(upload_to='budgets/%Y/%m/')),
                ('extraction_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('EXTRACTED', 'Extracted'), ('FAILED', 'Failed'), ('MANUAL_REVIEW', 'Manual Review Required')], default='PENDING', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budgets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_above_the_line', models.BooleanField(default=False)),
                ('is_local_eligible', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='projects.budget')),
            ],
            options={
                'db_table': 'budget_line_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('FEATURE', 'Feature Film'), ('TV_SERIES', 'TV Series'), ('DOCUMENTARY', 'Documentary'), ('COMMERCIAL', 'Commercial')], max_length=20)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='English', max_length=50)),
                ('synopsis', models.TextField(blank=True)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('shoot_start_date', models.DateField(blank=True, null=True)),
                ('shoot_end_date', models.DateField(blank=True, null=True)),
                ('shoot_duration_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UPLOADED', 'Budget Uploaded'), ('ANALYZING', 'Analyzing'), ('REVIEW', 'In Review'), ('COMPLETE', 'Complete'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.project'),
        ),
    ]
