# Generated by Django 5.0.14 on 2026-06-11 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cast_crew_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="project",
            name="production_timeline",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="project",
            name="script_file",
            field=models.FileField(blank=True, null=True, upload_to="scripts/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="project",
            name="shooting_plan_file",
            field=models.FileField(
                blank=True, null=True, upload_to="shooting_plans/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="spend_estimates",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="project",
            name="vetting_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="vetting_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="vetting_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vetted_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="vetting_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Review"),
                    ("FLAGGED", "Flagged for Review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
