# Generated by Django 5.0.14 on 2026-07-23 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_phase1_model_extensions"),
        ("territories", "0003_territory_film_commission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="target_territory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="target_projects",
                to="territories.territory",
            ),
        ),
    ]
