# Generated by Django 5.0.14 on 2026-07-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_target_territory"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="revenue_overrides",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
