# Generated by Django 5.0.14 on 2026-07-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_revenue_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="creative_staff_local_resident",
            field=models.BooleanField(default=False),
        ),
    ]
