# Generated by Django 5.0.14 on 2026-07-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_creative_staff_local_resident"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetlineitem",
            name="actual_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="budgetlineitem",
            name="commitment_status",
            field=models.CharField(
                choices=[
                    ("BUDGETED_UNCOMMITTED", "Budgeted / Uncommitted"),
                    ("BUDGETED_COMMITTED", "Budgeted / Committed"),
                    ("ACTUAL", "Actual"),
                ],
                default="BUDGETED_UNCOMMITTED",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="budgetlineitem",
            name="rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="budgetlineitem",
            name="units",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="budgetlineitem",
            name="vendor_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="diligence_controls",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="project",
            name="director",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="draw_schedule",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="project",
            name="executive_producer",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
